tasks:
  - init: |
    command: >
    cd /tmp &&
    curl -O https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh &&
    bash Anaconda3-2019.03-Linux-x86_64.sh &&
    source ~/.bashrc &&
    cd /workspace/OpenWPM &&
    conda activate openwpm &&
    ./install.sh
