tasks:
  - init: cd /tmp
    command: >
        curl -O https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh
        bash Anaconda3-2019.03-Linux-x86_64.sh
        source ~/.bashrc
        

